### PR TITLE
Model selector accessibility fixes

### LINKED ISSUE #414: Select a model - screen reader issues
## Environment

Localhost on `main` branch, Safari and Chrome browsers, VoiceOver 

## Expected Behavior:

When opening the ModelSelector component, the model names and currently selected model should be announced to screen reader users.

## Actual Behavior:

Model names are not announced as shown visibly. Instead, they are all announced as "model-item" and do not indicate the selected state audibly as shown by the checkmark on screen for the selected model.

Additionally, there are GSA logos next to each model name _(EDIT: These seem to be GSA-only logos in local environments)_. ~~These are likely not needed and likely are misleading for the models' actual logos.~~ They also have generic `alt` text which are not accurate or needed.

## Description

**Bug Summary:**
`aria-label`s are being misused in the ModelSelector component. Removing the `aria-label`s will allow the model text to be read as the accessible name for each `button` element.

## Logs and Screenshots

**Screen Recording (if applicable):**

https://github.com/user-attachments/assets/d2f6b703-0ccc-47de-aa81-81620ea78246

### PR DESCRIPTION
**Pull request by iamjolly**
# Changelog Entry

### Description

- Improves accessibility of the model selector component

### Added

- Screen reader announcement when model is changed.
- `role` and `alt` for check (checkmark icon) component

### Changed

- Removed incorrect usages of `aria-label` 

### Fixed

- this resolves #414

### CODE REVIEW

File: src/lib/components/chat/ModelSelector.svelte [hunk 1]
```diff
@@ -39,7 +39,7 @@
 				<div class="mr-1 max-w-full">
 					<Selector
 						id={`${selectedModelIdx}`}
-						placeholder={$i18n.t('Select a model')}
+						placeholder={selectedModel + ' is selected. ' + $i18n.t('Select a model')}
```
Comment (iamjolly) [inline src/lib/components/chat/ModelSelector.svelte:42]: Would like to pull in the model name as displayed instead of the string for the model like `bedrock_llama32_11b_pipeline`

Comment (iamjolly) [reply src/lib/components/chat/ModelSelector.svelte]: Thanks to @echappen this is resolved.
